# Generated by Django 5.2.14 on 2026-05-08 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('sido', models.CharField(max_length=30)),
                ('sigungu', models.CharField(max_length=30)),
                ('region_label', models.CharField(max_length=60)),
                ('main_category', models.CharField(max_length=30)),
                ('target_age', models.CharField(max_length=30)),
                ('preferred_time', models.CharField(max_length=30)),
                ('budget_range', models.CharField(max_length=30)),
                ('representative_text', models.TextField(blank=True)),
                ('centroid', models.JSONField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=3)),
                ('progress_ratio', models.FloatField(default=0.0)),
                ('remaining_count', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('COLLECTING', '요청 수집 중'), ('READY', '프로그램 생성 가능'), ('PROGRAM_CREATED', '프로그램 생성 완료')], default='COLLECTING', max_length=30)),
                ('fair_score', models.FloatField(default=50.0)),
                ('fair_reason', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CultureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=30)),
                ('sigungu', models.CharField(max_length=30)),
                ('region_label', models.CharField(blank=True, max_length=60)),
                ('main_category', models.CharField(choices=[('TRADITION', '전통문화'), ('PERFORMANCE', '공연'), ('EXHIBITION', '전시'), ('EXPERIENCE', '체험'), ('ETC', '기타')], default='ETC', max_length=30)),
                ('target_age', models.CharField(choices=[('ALL', '전체'), ('TEEN', '청소년'), ('YOUTH', '청년'), ('SENIOR', '고령층')], default='ALL', max_length=30)),
                ('preferred_time', models.CharField(choices=[('WEEKDAY_MORNING', '평일 오전'), ('WEEKDAY_AFTERNOON', '평일 오후'), ('WEEKDAY_EVENING', '평일 저녁'), ('WEEKEND_MORNING', '주말 오전'), ('WEEKEND_AFTERNOON', '주말 오후'), ('WEEKEND_EVENING', '주말 저녁')], default='WEEKEND_AFTERNOON', max_length=30)),
                ('budget_range', models.CharField(choices=[('FREE', '무료'), ('UNDER_10000', '1만원 이하'), ('UNDER_30000', '3만원 이하'), ('UNDER_50000', '5만원 이하'), ('ANY', '상관없음')], default='FREE', max_length=30)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='api.requestcluster')),
            ],
        ),
        migrations.CreateModel(
            name='CultureProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('place_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=80)),
                ('is_local_creator', models.BooleanField(default=True)),
                ('is_small_creator', models.BooleanField(default=True)),
                ('is_traditional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='api.requestcluster')),
            ],
        ),
    ]
