# Generated by Django 5.2.14 on 2026-05-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='군집 제목')),
                ('summary', models.TextField(blank=True, default='', verbose_name='군집 요약')),
                ('sido', models.CharField(blank=True, default='', help_text='예: 서울, 인천, 강원도, 전라도', max_length=50, verbose_name='시/도')),
                ('sigungu', models.CharField(blank=True, default='', help_text='예: 중구, 춘천시, 전주시', max_length=50, verbose_name='시/군/구')),
                ('region_label', models.CharField(blank=True, default='', help_text='예: 인천 중구, 강원도 춘천시', max_length=100, verbose_name='지역 표시명')),
                ('main_category', models.CharField(blank=True, default='', max_length=50, verbose_name='대표 문화 분야')),
                ('target_age', models.CharField(blank=True, default='전체', max_length=50, verbose_name='주요 대상')),
                ('preferred_time', models.CharField(blank=True, default='', max_length=50, verbose_name='대표 선호 시간대')),
                ('budget_range', models.CharField(blank=True, default='', max_length=50, verbose_name='대표 예산 범위')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='요청 수')),
                ('threshold', models.PositiveIntegerField(default=5, verbose_name='프로그램 생성 기준 요청 수')),
                ('status', models.CharField(choices=[('GATHERING', '요청 수집 중'), ('READY', '프로그램 생성 가능'), ('PROPOSED', '프로그램 후보 생성됨'), ('CLOSED', '종료')], default='GATHERING', max_length=20, verbose_name='군집 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '요청 군집',
                'verbose_name_plural': '요청 군집 목록',
                'ordering': ['-request_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CultureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_nickname', models.CharField(blank=True, default='익명', max_length=50, verbose_name='요청자 닉네임')),
                ('title', models.CharField(max_length=150, verbose_name='요청 제목')),
                ('content', models.TextField(help_text='사용자가 자유롭게 작성한 문화 요청 내용', verbose_name='요청 내용')),
                ('sido', models.CharField(help_text='예: 인천, 강원도, 전라도', max_length=50, verbose_name='시/도')),
                ('sigungu', models.CharField(help_text='예: 중구, 춘천시, 전주시', max_length=50, verbose_name='시/군/구')),
                ('region_label', models.CharField(blank=True, default='', help_text='예: 인천 중구, 강원도 춘천시', max_length=100, verbose_name='지역 표시명')),
                ('category', models.CharField(choices=[('TRADITIONAL', '전통문화'), ('PERFORMANCE', '공연'), ('EXHIBITION', '전시'), ('CRAFT', '공예'), ('MUSIC', '음악'), ('LOCAL', '지역문화'), ('CLASS', '체험/클래스'), ('ETC', '기타')], default='ETC', max_length=30, verbose_name='문화 분야')),
                ('target_age', models.CharField(choices=[('TEEN', '청소년'), ('YOUTH', '청년'), ('ADULT', '성인'), ('SENIOR', '고령층'), ('FAMILY', '가족'), ('ALL', '전체')], default='ALL', max_length=30, verbose_name='대상 연령')),
                ('preferred_time', models.CharField(choices=[('WEEKDAY_MORNING', '평일 오전'), ('WEEKDAY_AFTERNOON', '평일 오후'), ('WEEKDAY_EVENING', '평일 저녁'), ('FRIDAY_EVENING', '금요일 저녁'), ('SATURDAY_MORNING', '토요일 오전'), ('SATURDAY_AFTERNOON', '토요일 오후'), ('SUNDAY_AFTERNOON', '일요일 오후'), ('ANYTIME', '상관없음')], default='ANYTIME', max_length=30, verbose_name='선호 시간대')),
                ('budget_range', models.CharField(choices=[('FREE', '무료'), ('UNDER_30000', '3만원 이내'), ('UNDER_50000', '5만원 이내'), ('UNDER_100000', '10만원 이내'), ('OVER_100000', '10만원 이상')], default='UNDER_30000', max_length=30, verbose_name='예산 범위')),
                ('mobility_limit', models.CharField(blank=True, default='', help_text='예: 대중교통 가능, 도보 20분 이내, 이동 제약 있음', max_length=100, verbose_name='이동 제약 조건')),
                ('keywords', models.CharField(blank=True, default='', help_text='AI/키워드 군집화에 사용할 키워드', max_length=255, verbose_name='추출 키워드')),
                ('status', models.CharField(choices=[('SUBMITTED', '요청 등록'), ('CLUSTERED', '군집 연결 완료'), ('USED_FOR_PROGRAM', '프로그램 후보 반영'), ('ARCHIVED', '보관')], default='SUBMITTED', max_length=30, verbose_name='요청 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='places.requestcluster', verbose_name='연결된 요청 군집')),
            ],
            options={
                'verbose_name': '문화 요청',
                'verbose_name_plural': '문화 요청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
