# Generated by Django 5.2.14 on 2026-05-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_requestcluster_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='창작자 이름')),
                ('region_label', models.CharField(max_length=100, verbose_name='활동 지역')),
                ('category', models.CharField(max_length=50, verbose_name='활동 분야')),
                ('description', models.TextField(blank=True, default='', verbose_name='소개')),
                ('is_local_creator', models.BooleanField(default=True, verbose_name='지역 창작자 여부')),
                ('is_traditional', models.BooleanField(default=False, verbose_name='전통문화 관련 여부')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='연락처')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '창작자',
                'verbose_name_plural': '창작자 목록',
                'ordering': ['region_label', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='공간명')),
                ('region_label', models.CharField(max_length=100, verbose_name='위치')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='주소')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='수용 인원')),
                ('available_time', models.CharField(blank=True, default='', max_length=100, verbose_name='사용 가능 시간')),
                ('good_for', models.CharField(blank=True, default='', max_length=150, verbose_name='적합한 프로그램')),
                ('description', models.TextField(blank=True, default='', verbose_name='공간 설명')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '공공공간',
                'verbose_name_plural': '공공공간 목록',
                'ordering': ['region_label', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='프로그램 제목')),
                ('description', models.TextField(blank=True, default='', verbose_name='프로그램 설명')),
                ('expected_fee', models.CharField(blank=True, default='무료', max_length=50, verbose_name='예상 참가비')),
                ('expected_time', models.CharField(blank=True, default='', max_length=100, verbose_name='예상 시간')),
                ('status', models.CharField(choices=[('DRAFT', '제안 준비 중'), ('RECRUITING', '참여자 모집 중'), ('CONFIRMED', '진행 확정'), ('CLOSED', '종료')], default='DRAFT', max_length=20, verbose_name='상태')),
                ('accessibility_note', models.CharField(blank=True, default='', max_length=255, verbose_name='접근성 설명')),
                ('cultural_context', models.TextField(blank=True, default='', verbose_name='문화적 맥락 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='places.requestcluster', verbose_name='연결된 문화콜')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='places.creator', verbose_name='창작자')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='places.publicspace', verbose_name='공간')),
            ],
            options={
                'verbose_name': '프로그램 제안',
                'verbose_name_plural': '프로그램 제안 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
