# Generated by Django 5.2.14 on 2026-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_creator_publicspace_programproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcluster',
            name='threshold',
            field=models.PositiveIntegerField(default=3, verbose_name='프로그램 생성 기준 요청 수'),
        ),
    ]
